---
- name: Set up user
  user: name={{username}} shell="/bin/bash"

- name: Install Java dependencies
  yum: name={{ item }} state=present
  with_items:
    - java-1.7.0-openjdk

#Async operation
#- name: yum update
#action: command yum -y update
#async: 7200
#poll: 15

- name: Create SU-TO-appname shortcut
  template: src=su-to-user.sh dest=~/{{app_name}}_su_to.sh mode=744
  sudo: false

- name: Create restart-service shortcut
  template: src=restart-service.sh dest=~/restart-{{app_name}}.sh mode=744
  sudo: false

- name: App update script
  template: src=update-service.sh dest=/home/{{username}}/update-service.sh mode=744
  sudo_user: "{{username}}"

- name: Fetch Latest greatest version of App
  command: /home/{{username}}/update-service.sh chdir=/home/{{username}}
  sudo_user: "{{username}}"

- name: Create start-Service.sh script
  template: src=start-service.sh dest=/home/{{username}}/start-service.sh mode=744 backup=true
  sudo_user: "{{username}}"

- name: App upstart conf
  template: src=service-upstart.conf.jinja dest=/etc/init/{{app_name}}.conf owner=root mode=644 backup=true

- name: ReStart App service
  service: name="{{app_name}}" state=restarted


#### Test that service works:
- wait_for: port={{service_port}} delay=5 timeout=30

- name: Test that service responds
  get_url: url={{verify_service_url}} dest=/tmp/test_{{app_name}} force=true
  when: verify_service_url is defined
  register: result

- debug: msg="{{result}}"